btn = {
    'start': '/start',
    'yes': 'Да',
    'no': 'Нет',
    'begin': 'Начать',
    'buy forecast': 'Купить прогноз',
    'watch': 'Посмотреть видео',
    'survey': 'Пройти опрос',
    'continue': 'Продолжить',
    'unsubscribe': 'Отписаться',
    'details': 'Узнать детали',
    'pay': 'Оплатить',
    'pay1500': 'Оплатить 1500 РУБ',
    'termins': 'Посмотреть термины',
    'user amount': 'Количество пользователей',
    'unsubscribed users': 'Отписавшиеся пользователи',
    'dispatch': 'Рассылка',
    'direct message': 'Сообщение по чат-айди',
    'forecast': 'Залить прогноз',
    'added_forecasts': 'Залитые прогнозы',
    'admit': 'Подтвердить',
    'decline': 'Отменить',
    'feedbacks': 'Отзывы',
    'to_beginning': 'В начало',
}